default: &default
  adapter: postgresql
  encoding: unicode
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: basile_quinchon_refonte_development

test:
  <<: *default
  host: localhost
  username: postgres
  database: basile_quinchon_refonte_test

production:
  <<: *default
  database: basile_quinchon_refonte_production
  username: basile_quinchon_refonte
  password: <%= ENV['BASILE_QUINCHON_REFONTE_DATABASE_PASSWORD'] %>
