env:
  RUBY_VERSION: 2.6.6
name: Rubocop
description: "Rubocop action"
on: [push, pull_request]
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v1
  - uses: actions/setup-ruby@v1
    with:
      ruby-version: ${{ env.RUBY_VERSION }}
  - name: Install Rubocop
    run: gem install rubocop
  - name: Check code
    run: rubocop

