env:
  RUBY_VERSION: 2.6.6
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  DB_HOST: localhost
  DEVELOPER_EMAIL_ADDRESS: "basile.quinchon@gmail.com"
name: Rails tests
on: [push, pull_request]
jobs:
  everything:
    name: Do stuffs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rubocop
      uses: ./.github/workflows/rubocop
    - name: rspec
      needs: rubocop
      uses: ./.github/workflows/rspec
    - name: build
      needs: rspec
      uses: ./.github/workflows/build
